[project]
name = "hitchenv-hitchstory"
version = "0.0.0"
requires-python = ">=3.14.0"
dependencies = ["hitchpylibrarytoolkit"]

[tool.uv.sources]
hitchpylibrarytoolkit = { path = "../hitchpylibrarytoolkit", editable = true }
